export const CHANGE_EMOJI_EYEBROW_SUCCESS = 'CHANGE_EMOJI_EYEBROW_SUCCESS';
export const CLEAR_EMOJI_EYEBROW = 'CLEAR_EMOJI_EYEBROW';

export const CHANGE_EMOJI_EYES_SUCCESS = 'CHANGE_EMOJI_EYES_SUCCESS';
export const CLEAR_EMOJI_EYES = 'CLEAR_EMOJI_EYES';

export const CHANGE_EMOJI_MOUTH_SUCCESS = 'CHANGE_EMOJI_MOUTH_SUCCESS';
export const CLEAR_EMOJI_MOUTH = 'CLEAR_EMOJI_MOUTH';

export const CHANGE_EMOJI_MOOD_SUCCESS = 'CHANGE_EMOJI_MOOD_SUCCESS';
export const CLEAR_EMOJI_MOOD = 'CLEAR_EMOJI_MOOD';

export const RESET_EMOJI_PARTS_SUCCESS = 'RESET_EMOJI_PARTS_SUCCESS';

export const GET_EMOJI_SUCCESS = 'GET_EMOJI_SUCCESS';
